---
- hosts: all
  become: true

  handlers:
    - name: docker status
      service: name=docker state=started

  tasks:
  - name: Install system packages
    apt:
      name:
      - net-tools
      - iputils-ping
      - dnsutils
      - curl
      - jq

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - software-properties-common

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependencies
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    notify:
      - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl

  - name: Configure docker daemon
    lineinfile:
      path: /etc/docker/daemon.json
      line: "{ \"exec-opts\": [\"native.cgroupdriver=systemd\"] }"
      create: yes

  - name: Start docker service
    service:
      name: docker
      state: restarted
      daemon_reload: yes

  - name: Reset Kubernetes cluster
    command: kubeadm reset -f

  - name: Initialize the Kubernetes cluster
    command: kubeadm init --apiserver-advertise-address 192.168.56.10 \
                          --apiserver-cert-extra-sans 192.168.56.10 \
                          --pod-network-cidr 10.244.0.0/16 \
                          --node-name node-1

  - name: Create .kube folder
    file:
      path: "/home/{{ ansible_user }}/.kube"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0755

  - name: Copy file with owner and permissions
    copy:
      src: /etc/kubernetes/admin.conf
      dest: "/home/{{ ansible_user }}/.kube/config"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644
      remote_src: yes

  # By default, your cluster will not schedule Pods on the control-plane node for security reasons
  # https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
  - name: Taint node
    command: kubectl taint nodes --all node-role.kubernetes.io/master-
    become: false

  - name: Install the Tigera Calico operator and custom resource definitions
    command: kubectl create -f https://docs.projectcalico.org/master/manifests/tigera-operator.yaml
    become: false

  - name: Install Calico by creating the necessary custom resource
    command: kubectl create -f https://docs.projectcalico.org/master/manifests/custom-resources.yaml
    become: false

  - name: Create kube flannel run directory
    file:
      path: /run/flannel
      state: directory
      mode: 0755

  - name: Add subnet.env
    template:
      src: subnet.env.j2
      dest: /run/flannel/subnet.env

  - name: Apply kube flannel
    command: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
    become: false

  # ssh
  - name: Include ssh vault vars
    include_vars:
      file: vault.yaml

  - name: Copy ssh key id_rsa
    copy:
      content: "{{ mbp_id_rsa }}"
      dest: /home/{{ ansible_user}}/.ssh/mbp_id_rsa
      mode: 0600
      owner: "{{ ansible_user }}"
    no_log: True

  - name: Copy ssh key id_rsa.pub
    copy:
      content: "{{ mbp_id_rsa_pub }}"
      dest: /home/{{ ansible_user}}/.ssh/mbp_id_rsa.pub
      mode: 0644
      owner: "{{ ansible_user }}"
    no_log: True

  - name: Add id_host to ssh config
    lineinfile:
      line: " IdentityFile /home/{{ ansible_user }}/.ssh/mbp_id_rsa"
      dest: /home/{{ ansible_user }}/.ssh/config
      mode: 0644
      owner: "{{ ansible_user }}"
    no_log: True

  - name: Add github to known_hosts
    lineinfile:
      line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
      dest: /home/{{ ansible_user }}/.ssh/known_hosts
      mode: 0644
      owner: "{{ ansible_user }}"
      create: True
    no_log: True

  # git
  - name: Install git-core
    apt:
      name: git-core
    no_log: True

  - name: Configure git
    command: "{{ item.command }}"
    loop:
      - { command: "git config --global core.editor vim" }
      - { command: "git config --global core.pager less" }
    no_log: True

  - name: Add .gitconfig
    template:
      src: gitconfig
      dest: /home/{{ ansible_user }}/.gitconfig
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0644
    no_log: True
