---
  - name: Update apt sources.list
    command: echo 'deb http://ftp.plusline.net/debian/ unstable main contrib non-free' > /etc/apt/sources.list

  - name: Update all packages to their latest version
    apt:
      name: "*"
      state: latest

  - name: Install packages that allow apt to be used over https
    apt:
      name:
      - apt-transport-https
      - ca-certificates
      - gnupg
      - software-properties-common
      - lsb-release

  - name: Install system packages
    apt:
      name:
      - net-tools
      - iputils-ping
      - dnsutils
      - curl
      - jq
      - htop
