# ssh
---
- name: Include ssh vault
  tags: ssh
  include_vars:
    file: vault.yaml
  no_log: True

- name: Copy host private key
  tags: ssh
  copy:
    content: "{{ mbp_id_rsa }}"
    dest: "{{ ssh_private_key }}"
    mode: 0600
    owner: "{{ ansible_user }}"
  no_log: True

- name: Copy host public key
  tags: ssh
  copy:
    content: "{{ mbp_id_rsa_pub }}"
    dest: "{{ ssh_public_key }}"
    mode: 0644
    owner: "{{ ansible_user }}"
  no_log: True

- name: Create ssh config
  tags: ssh
  file:
    path: "{{ ssh_config }}"
    state: touch
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  no_log: True

- name: Add host private key to ssh config
  tags: ssh
  lineinfile:
    line: " IdentityFile {{ ssh_private_key }}"
    dest: "{{ ssh_config }}"
    mode: 0644
    owner: "{{ ansible_user }}"
  no_log: True

- name: Set authorized key took from file
  authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key:  "{{ lookup('file', '/Users/ngonzalez/.ssh/id_rsa.pub') }}"
  no_log: True

- name: Add github to known_hosts
  tags: ssh
  lineinfile:
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    dest: "{{ ssh_known_hosts }}"
    mode: 0644
    owner: "{{ ansible_user }}"
    create: True
  no_log: True
