---
# nginx-ingress
- name: Checkout nginxinc/kubernetes-ingress repository
  become_user: "{{ ansible_user }}"
  git:
    repo: "{{ nginx_ingress_repository }}"
    dest: "/home/{{ ansible_user }}/kubernetes-ingress"

- name: Create a namespace and a service account for the Ingress controller
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/ns-and-sa.yaml

- name: Create a cluster role and cluster role binding for the service account
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f rbac/rbac.yaml

- name: Create a secret with a TLS certificate and a key for the default server in NGINX
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/default-server-secret.yaml

- name: Create a config map for customizing NGINX configuration
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/nginx-config.yaml

- name: Create an IngressClass resource
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/ingress-class.yaml

- name: Create custom resource definitions for VirtualServer resource
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/crds/k8s.nginx.org_virtualservers.yaml

- name: Create custom resource definitions for VirtualServerRoute resource
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/crds/k8s.nginx.org_virtualserverroutes.yaml

- name: Create custom resource definitions for TransportServer resource
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/crds/k8s.nginx.org_transportservers.yaml

- name: Create custom resource definitions for Policy resource
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/crds/k8s.nginx.org_policies.yaml

- name: Create a custom resource definition for GlobalConfiguration resource
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/crds/k8s.nginx.org_globalconfigurations.yaml

- name: Create a custom resource definition for GlobalConfiguration resource
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f common/crds/k8s.nginx.org_globalconfigurations.yaml

- name: Run the Ingress Controller
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f daemon-set/nginx-ingress.yaml

- name: Create a Service for the Ingress Controller Pods
  become_user: "{{ ansible_user }}"
  shell:
    chdir: "{{ nginx_ingress_deployments_path }}"
    cmd: kubectl apply -f service/loadbalancer.yaml
